var data;
export default data = [
            {
                "fixture_id":"37562",
                "event_timestamp":"1533926700",
                "event_date":"2018-08-10T18:45:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"81",
                "awayTeam_id":"96",
                "homeTeam":"Marseille",
                "awayTeam":"Toulouse",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"4",
                "goalsAwayTeam":"0",
                "halftime_score":"1-0",
                "final_score":"4 - 0",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1533926700",
                "secondHalfStart":"1533930300"
            },
            {
                "fixture_id":"37561",
                "event_timestamp":"1533999600",
                "event_date":"2018-08-11T15:00:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"83",
                "awayTeam_id":"91",
                "homeTeam":"Nantes",
                "awayTeam":"Monaco",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"1",
                "goalsAwayTeam":"3",
                "halftime_score":"0-0",
                "final_score":"1 - 3",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1533999600",
                "secondHalfStart":"1534003200"
            },
            {
                "fixture_id":"37556",
                "event_timestamp":"1534010400",
                "event_date":"2018-08-11T18:00:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"77",
                "awayTeam_id":"92",
                "homeTeam":"Angers",
                "awayTeam":"Nimes",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"3",
                "goalsAwayTeam":"4",
                "halftime_score":"1-1",
                "final_score":"3 - 4",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1534010400",
                "secondHalfStart":"1534014000"
            },
            {
                "fixture_id":"37557",
                "event_timestamp":"1534010400",
                "event_date":"2018-08-11T18:00:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"79",
                "awayTeam_id":"94",
                "homeTeam":"Lille",
                "awayTeam":"Rennes",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"3",
                "goalsAwayTeam":"1",
                "halftime_score":"1-1",
                "final_score":"3 - 1",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1534010400",
                "secondHalfStart":"1534014000"
            },
            {
                "fixture_id":"37558",
                "event_timestamp":"1534010400",
                "event_date":"2018-08-11T18:00:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"82",
                "awayTeam_id":"89",
                "homeTeam":"Montpellier",
                "awayTeam":"Dijon",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"1",
                "goalsAwayTeam":"2",
                "halftime_score":"1-0",
                "final_score":"1 - 2",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1534010400",
                "secondHalfStart":"1534014000"
            },
            {
                "fixture_id":"37559",
                "event_timestamp":"1534010400",
                "event_date":"2018-08-11T18:00:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"84",
                "awayTeam_id":"93",
                "homeTeam":"Nice",
                "awayTeam":"Reims",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"0",
                "goalsAwayTeam":"1",
                "halftime_score":"0-1",
                "final_score":"0 - 1",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1534010400",
                "secondHalfStart":"1534014000"
            },
            {
                "fixture_id":"37560",
                "event_timestamp":"1534010400",
                "event_date":"2018-08-11T18:00:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"1063",
                "awayTeam_id":"90",
                "homeTeam":"Saint Etienne",
                "awayTeam":"Guingamp",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"2",
                "goalsAwayTeam":"1",
                "halftime_score":"1-0",
                "final_score":"2 - 1",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1534010400",
                "secondHalfStart":"1534014000"
            },
            {
                "fixture_id":"37555",
                "event_timestamp":"1534078800",
                "event_date":"2018-08-12T13:00:00+00:00",
                "league_id":"4",
                "round":"Regular Season - 1",
                "homeTeam_id":"80",
                "awayTeam_id":"87",
                "homeTeam":"Lyon",
                "awayTeam":"Amiens",
                "status":"Match Finished",
                "statusShort":"FT",
                "goalsHomeTeam":"2",
                "goalsAwayTeam":"0",
                "halftime_score":"1-0",
                "final_score":"2 - 0",
                "penalty":"-",
                "elapsed":"90",
                "firstHalfStart":"1534078800",
                "secondHalfStart":"1534082400"
            }
]

